{% set version = "0.2.6" %}

package:
  name: scripting
  version: {{ version }}

source:
  url: https://github.com/csdms/py-scripting/archive/v{{ version }}.tar.gz
  fn: py-scripting-{{ version }}.tar.gz
  sha256: af266b767b65957137efa2adee7eca4436b70b48b3a47b9c958df7dbdcb9e75b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - setuptools
    - python
    - pip
  run:
    - python
    - pytest
    - six

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs scripting --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: https://github.com/csdms/py-scripting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utilities for shell scripting
  dev_url: https://github.com/csdms/py-scripting

extra:
  recipe-maintainers:
    - mcflugen
