{% set version = "0.2.4" %}

package:
  name: scripting
  version: {{ version }}

source:
  url: https://github.com/csdms/py-scripting/archive/v{{ version }}.tar.gz
  fn: py-scripting-{{ version }}.tar.gz
  sha256: 9d262e210ce2129df07716b528cef079bd655c2aacfa63d63971143ad8c9cdf3

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - setuptools
    - python
    - pip
  run:
    - python
    - pytest
    - six

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs scripting --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

about:
  home: https://github.com/csdms/py-scripting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utilities for shell scripting
  dev_url: https://github.com/csdms/py-scripting

extra:
  recipe-maintainers:
    - mcflugen
