travis:
  secure:
    BINSTAR_TOKEN: PyMstBaXZYasVfRDsXd+T0e8Z+UYzcBXxOx/l9AVyiN/ho44tNc1zvejNKsFN2uqqDf6A5btXFlJs3Q7jk3HpXjsXLt+afu4f3aD+K6eeTVL2y7QTggzQs37CubKKV7jUFGchfSakJmuBZV2aot+aln3DXfTQHiMparP6wpFCJkHxY+Mz3QS22WRoTkwHUHB5gu7RKgtbHdVFPVULWCeZLUJ+m2K61rY7nSE05c5XWy4RbqG5w/Tl1lc4zC3V2UPlD3oqya4sVHYjMHa5iCReaFdYyFhDOrwJE2iPib87bKuxpHLUCfUwkxlU/7/bnoWhPOjm+73S5oU+XU03DHg+KPgcaZ53B+0YbcHgGUMSeIjHg9GUYDich3ccKt1iBVw6D8qSA5OPu6ZwuRMudvKXd272slM5Jo7kY7XqXb+f5qhi7E1Toz9Ku7HtxphTifUMzh0bqcOdF0wUYXnrIekIgbCxc9Wja1f/gdUC68Po6b/0aZPrOc7iOyHW1Xn/LMENtDlp1bSiWcbHn6IA0qrJjzkCA1gtnniFo+pvceI1kkTpShMKOwzMg91XIQun0hvhJDRk6Jbyk0upv1J1lAp2dWw74b/8EdTmDH1z6HHEMAxbPb4skaVprlr1PX4z1yKD/d5JxhoomRQMgkrXTeHnG0XMPS+bpd6N8F2uLa9xes=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
